# Some JPEGImageReader tests fail on OpenJDK, need to investigate/fix before enabling
#  - openjdk7
branches:
  only:
  - master
  - stable
language: java
env:
  global:
  - secure: WOPIlSH74d4sQrTr2KQOQjovMEzHYoRY4qsu9QtOMnLwyb/+WaD4nfDSOuReI0FEbU3VVStixmDrUGeiwnmrS6RAPiBLzzgXJv7L93m/JTx706ss9UcOx16+w4QcHFcItCqnWf+j1WmhD5dkeQwbA4xTHOmAI46wK7gXkpALfjQhpasTDJBfFOtYKc9ehoGOsjOSXdUZfpy9rlNcuJ3NnOYAlvrTcmPw5AWegyZreQOxXbK/oAHQUGlZ+mPdpKq7NR0eyyaxFgsaoNxEyZb/zWCI8aF0Di5hNskSnr7Y89X1UL6KTeQIhzPhHefBTUD4Ai5GzyW1a1FwXxZLuz2WP3/gQ1REV7lALutMorLKhgXipcRE60EAJSXH1QWDWCgMw5oFFafx7fGpvwOldQiO322sX1YhGr/IOTs2bhwzu4j85M1WrBXIvf78ysCZzz1z1jhoTepVWdUmdN1W5JvhRYqVEo6aRvV75Vrg8w0Q2elZYo9GTJ7ETO4xEw0HWD10ZiBWsPIpZEa5gd/FuSRkTmV0+wn7HPj/X/yyNMtwFnMoh+GVPp3dfkIeTAjdfXYrPqQfITDt6lKtY9aw4+zlH6krUD7K30nAkSuNkTxLGyY8/sYjDb/YPmb7HYXQZMA7gCVRraLQBEmL1BbHmBox0DG6f6hEbk2zv373W+qji2E=
  - secure: WkRyJ24iVf7aHgciO7/tgybed1A8V9ps5nWHlYU+l/ldtqQWfpW0mj+TIKXUblsZ0YDHPtIPIzbEEZgSAJZThZQ8cC5YCkNFCdp2CAxr2U2KNvO+MQZGgcJPb7sCTNDU+OiXJsfm1Xqj24khn+FGwnV+C1Yo6S2x4cnVff2i1yykdcrP+vskoVA/tYh8OdYBOdwOQn7SHwN5doWABoriMLAs/OuLhvU143UZAZtmpxx+5jeAGmnsDpMPgyGU67/S0bcuDNAsX10MDH8Nn7azFvHzAvnj0nXk8MNIRo4alytCqql1FdkcQ2hrGx/Jp13DVTkofjH6qpYom+IaQwBJsGcKaJkGAKjwnTSRU4no6qWFMIvZTI7twbtKUa63IgovkAdkwipahkcLs9B7vvzgVL+C6JbNXM6CltCruQ+nSQ/ceI/1WLbmcocrrEsK5O3y/jtEaObzQ+OqOYHn7gUmNAEMRwcTgbaNPCaT0FCO6cV2p51Yc8WM4RDMDthcNrWlO9ZLYe8UL8nOjKZvEdSHSGdRB2S67e4cyfZMN6HRraZWrSHsMS3wrhijMdklhAQ8zVQIMzzzni4Srm76XLDTIqCT/iVTM56MTeKDkYjw6Pk+McB8nqfn9MxR2NamqTebcqslDOm/7rTVKb3XFlMYLbhorlvaAqeTtHsmjdMI0F0=
  - secure: xAar5EYh1BMDcBC9nyuR1GaBGUBVQTDN1S/8du56QSzl03UMSvP0ONqugkxjwYuxPMFIMRFDU4fsSgWqG+iNMOrwaSXZXlApjGG0QM466P/2/p2VwrthFI8DlncCvFcgSfOgrqNKLrjj+fJ4o7hU67cEwqKh+L9jQdXJ4Vz4b36fRvnoD0c+K2Yce1QriihI8V3UUGMDZPy9+8V4IVJV9AIta3h5PgIBluiHQTQACtePiTQdlpKdUMdftSAx7h9N5jjwY6+QsNJPSD2Abw8jFCHrFoQmKusPmlUoccjMcJ+NOAxYBma09G1cPv+V+8yrgwtyWAeWL1Jk4bCHrksaROJfcuK8Y8rig8LkP7k+csEFy73lPcLNOHnNhX6wxU0ceHPVtAk7q3aUBmioeHlJKvFXZi+1WYEvFjhNPuW/yJp3nBGdXMYNCuJ6L9BKLP9SM1NDqN5iZWVOPj5LiORONasYqZy1LvYlkVSDdNqSg+OCQTVPKG3XZUFNY+9CdmLPby7U6aJ7fCmTpPz0umOqHWQnSpXgPSHpV06RzXEfelUbWrq54zNUawTMtgrjuCziMwupV2Y2hJwKQinbgjho3CpoQXS8d7JB2GEJSFMBJvTaUt+/7zyeV/nwhZzBNR/viojQo3yNQ23Kdhne8Nh2k+Wrpu/wLic5ZQ8h8BgCBbQ=
  - secure: mnTmmYV+fTV0rKb1fiid5Y+rZBsH2csw2Cd14rVEsaJUGQDQ0RavyId4jZr3NzRKw+5OsWYgGCTzhOZzhMLFvrQc5m06wcdBeDaV2n3ijt13G272mI9pdgaOYnqdGJM+OAm49fA9ipL7ftz1KYEFdQanzLk062RKPZ5I4QxUyWUcQgR7NSFkZ+e0j+kJuGH2xaQaZJ/12Ms513Vm1uaUjLHj9lvmhsFGQpklODoalR4S5adXeUZa6o+ymIPzLmlKMkLzA7p5BRDPlcdlVxmlb66yR4YmKEDQPNVGLOcqgYl7jtkd7jalYi8BUTtbKyjJBL/c8SvBCIuXHMVw7tUZQkAsKK0QS29Bl8ZSlXvlmMqnNpOQc42tqrJtj1vxfawF2hHmmKDZ3XjrF723VhqsuAfZNSo11BXn+BXYp6HX5BKJ3ub1m/xObSQPxZ3QDtdpO/dE5lHXB+kRYG+wIgqxqimM7TpH5JkT2+RAOzD9B0UhgQxeLGjp5BjSwKERfMXwLipPEval0PpeiCL8lOHPCAT5h6KG5wZ3/mFcuf19Ubgu/PxQ0K/1CmySx6EChNI5bSuAFxu4usDRnn3hF1yIj5H/lvHC4nTQLqvwH4qnrDWIY7I8spc8M9BV4XJbsykCQ2P3sUFCqRjvQweVeQd2XViZ18yz4a8xk7ciakGm+qs=
jdk:
- oraclejdk8
install:
- mvn clean install -DskipTests=true -P !build-extras -B -V
before_script: 
script: mvn test -am -P !build-extras -B
cache:
  directories:
  - "~/.m2/repository"
after_success:
- "./cd/before-deploy.sh"
- "./cd/deploy.sh"
after_failure:
- cat com.github.lafa.logfast/target/surefire-reports/*.txt
- cat com.github.lafa.logfast/core/target/surefire-reports/*.txt
